# Generated by Django 5.2.16 on 2026-09-16 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('spell', 'Заклинание'), ('creature', 'Существо'), ('item', 'Предмет'), ('class', 'Класс'), ('race', 'Раса'), ('feat', 'Черта'), ('background', 'Предыстория')], db_index=True, max_length=20, verbose_name='Тип')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (англ.)')),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='Слаг')),
                ('sources', models.JSONField(default=list, verbose_name='Источники')),
                ('content_html', models.TextField(verbose_name='HTML карточки')),
                ('content_text', models.TextField(verbose_name='Текст для поиска')),
                ('data', models.JSONField(default=dict, verbose_name='Данные типа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Сущность энциклопедии',
                'verbose_name_plural': 'Сущности энциклопедии',
                'ordering': ['entity_type', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EntityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=255, verbose_name='Текст ссылки')),
                ('from_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='encyclopedia.entity', verbose_name='От сущности')),
                ('to_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_from', to='encyclopedia.entity', verbose_name='К сущности')),
            ],
            options={
                'verbose_name': 'Связь сущностей',
                'verbose_name_plural': 'Связи сущностей',
                'ordering': ['from_entity_id', 'to_entity_id'],
                'constraints': [models.UniqueConstraint(fields=('from_entity', 'to_entity', 'text'), name='unique_entity_link')],
            },
        ),
    ]
