# Generated by Django 5.2.16 on 2026-09-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('spell', 'Заклинание'), ('creature', 'Существо'), ('item', 'Предмет'), ('class', 'Класс'), ('race', 'Раса'), ('feat', 'Черта'), ('background', 'Предыстория'), ('sidekick', 'Сайдкик')], db_index=True, max_length=20, verbose_name='Тип'),
        ),
    ]
