# Generated by Django 5.2.16 on 2026-07-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_choice_image_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.CharField(max_length=50, verbose_name='ID анкеты')),
                ('player_name', models.CharField(max_length=50, verbose_name='Имя участника')),
                ('answers', models.JSONField(verbose_name='Ответы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Пройдена')),
            ],
            options={
                'verbose_name': 'Результат анкеты',
                'verbose_name_plural': 'Результаты анкет',
                'ordering': ['-created_at'],
            },
        ),
    ]
