# Generated by Django 5.2.16 on 2026-07-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_surveysubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysubmission',
            name='character_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Имя персонажа'),
        ),
    ]
