# Generated by Django 5.2.16 on 2026-09-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_surveysubmission_character_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('code_hash', models.CharField(max_length=64, verbose_name='Хэш кода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попытки ввода')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
            ],
            options={
                'verbose_name': 'Код входа по email',
                'verbose_name_plural': 'Коды входа по email',
                'ordering': ['-created_at'],
            },
        ),
    ]
